services:
  fcd:
    pull_policy: build
    container_name: hw3_shevchenko_fcd
    networks:
      - net
    image: facade_service
    build:
      context: facade_service
    ports:
      - 8080:8080
    environment:
      - GIN_MODE=release
      - LOG_ADDRESSES=http://log1:8080/log,http://log2:8080/log,http://log3:8080/log
      - MSG_ADDRESSES=http://msg:8080/msg
    depends_on:
      msg:
        condition: service_started
      log1:
        condition: service_started
      log2:
        condition: service_started
      log3:
        condition: service_started

  msg:
    pull_policy: build
    container_name: hw3_shevchenko_msg
    networks:
      - net
    image: messaging_service
    build:
      context: messaging_service
    ports:
      - 8081:8080
    environment:
      - GIN_MODE=release


  log1:
    pull_policy: build
    container_name: hw3_shevchenko_log1
    networks:
      - net
    image: logging_service
    build:
      context: logging_service
    ports:
      - 8082:8080
    environment:
      - GIN_MODE=release
      - HZ_ADDRESS=node1:5701
    depends_on:
      node1:
        condition: service_healthy
  log2:
    pull_policy: build
    container_name: hw3_shevchenko_log2
    networks:
      - net
    image: logging_service
    build:
      context: logging_service
    ports:
      - 8083:8080
    environment:
      - GIN_MODE=release
      - HZ_ADDRESS=node2:5701
    depends_on:
      node2:
        condition: service_healthy
  log3:
    pull_policy: build
    container_name: hw3_shevchenko_log3
    networks:
      - net
    image: logging_service
    build:
      context: logging_service
    ports:
      - 8084:8080
    environment:
      - GIN_MODE=release
      - HZ_ADDRESS=node3:5701
    depends_on:
      node3:
        condition: service_healthy


  node1:
    container_name: hw3_shevchenko_node1
    networks:
      - net
    ports:
      - 5701:5701
    image: hazelcast/hazelcast:latest
    healthcheck:
      test: curl --fail http://localhost:5701/hazelcast/health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      - HZ_CLUSTERNAME=hw3_shevchenko_hazelcast
      - HZ_QUEUE_BOUNDEDQUEUE_MAXSIZE=10
  node2:
    container_name: hw3_shevchenko_node2
    networks:
      - net
    ports:
      - 5702:5701
    image: hazelcast/hazelcast:latest
    healthcheck:
      test: curl --fail http://localhost:5701/hazelcast/health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      - HZ_CLUSTERNAME=hw3_shevchenko_hazelcast
      - HZ_QUEUE_BOUNDEDQUEUE_MAXSIZE=10
  node3:
    container_name: hw3_shevchenko_node3
    networks:
      - net
    ports:
      - 5703:5701
    image: hazelcast/hazelcast:latest
    healthcheck:
      test: curl --fail http://localhost:5701/hazelcast/health
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s
    environment:
      - HZ_CLUSTERNAME=hw3_shevchenko_hazelcast
      - HZ_QUEUE_BOUNDEDQUEUE_MAXSIZE=10
  
  ui:
    networks:
      - net
    container_name: hw3_shevchenko_ui
    ports:
      - 8090:8080
    image: hazelcast/management-center:latest

networks:
  net:
    name: hw3_shevchenko_network
    driver: bridge
